version: 2.1
commands:
  checkout_and_bundle_install:
    description: "Checkout the code and bundle install"
    steps:
      - checkout
      - restore_cache:
          keys:
            - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
            - rails-demo-bundle-v2-
      
      - run:
          name: Force Bundler Version
          command: |
            sudo gem update --system
            gem install bundler
      - run:
          name: Bundle Install
          command: bundle check || bundle install

      - save_cache:
          key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

workflows:
  cucumber:
    jobs:
      - Automacao Desafio Compasso - Livelo

jobs:
  cucumber:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
        environment:
          ALLOW_DB_SEEDS: true
          BUNDLE_JOBS: 2
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          CUCUMBER_HEADLESS: true
          RAILS_ENV: test
          DATABASE_URL: postgresql://postgres:@localhost/desafio_compasso-livelo
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: desafio_compasso-livelo
          POSTGRES_PASSWORD: ""
      
    steps:
      - run:
          name: Update binaries
          command: sudo apt-get update && sudo apt-get install -y ghostscript qt5-default libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x
      - checkout_and_bundle_install

      - run:
          name: Run cucumber
          command: bundle exec cucumber --retry 2